version: '3'
services:
  web:
    image: "docker-node-mongo-todo-app"
    build: .
    command: "node server.js"
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
